pipeline {
    agent {
	label "jenkins-agent"
    }
    
    
     environment {
           APP_NAME = "complete-prodcution-e2e-pipeline"
    }
    


    stages{
        stage("Checkout from SCM"){
            steps {
                git branch: 'main', credentialsId: 'github', url: 'https://github.com/iam-arellano/gitops-argocd-image-updater'
            }
        }
	
	    stage("Update the Deployment tags"){
            steps {
                sh """
		            cat deployment.yaml
		            sed-i 's/${APP_NAME}.*/${APP_NAME}:${IMAGE_TAG}/g' deployment.yaml
		            cat deployment.yaml
		        """
            }
        }

        stage("Push the changed deployment file to git "){
            steps {
                sh """
		  git config user.email "raemond.arellano01@gmail.com"
                  git config user.name "Raemond Arellano"
                  git add deployment.yaml
                  git commit -m "Update Deployment Manifest"
		        """
             // If private repo you need to add this credentials   
            //withCredemtials([gitUsernamePassword(credentialsId: 'github-pat',gitToolName: 'Default')])
            sh "git push https://github.com/iam-arellano/gitops-argocd-image-updater main"
            }
        }
 	}
 }
